apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geth-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: premium-rwo # Uncomment if you need to change the storageClass different than the default
