name: deploy

on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: start geth
        run: |
          docker compose -f docker-compose.yml up -d
          
      - name: wait geth
        run: sleep 20

      - name: install hardhat deps
        run: |
          cd ./hardhat
          npm install

      - name: deploy contract
        run: |
          cd ./hardhat
          npx hardhat compile
          yes | npx hardhat ignition deploy ./ignition/modules/Lock.ts --network geth

      - name: Shutdown services
        if: always()
        run: docker compose -f docker-compose.yml down
